more implementation

diff --git a/bin/bw-backup b/bin/bw-backup
--- a/bin/bw-backup
+++ b/bin/bw-backup
@@ -33,7 +33,7 @@ usage() {
     echo "    -r, --recipient RECIPIENT      Encrypt to the specified RECIPIENT (public key). May be repeated."
     echo "    -R, --recipients-file PATH     Encrypt to the recipients (public keys) listed at PATH. May be repeated."
     echo "    -b, --backup-dir PATH          Use the directory at PATH to store the encrypted backup."
-    echo "    -n, --name NAME                Set a name to include in the backup file name."
+    echo "    -p, --prefix PREFIX            Set a prefix for the backup file name."
     echo "    -u, --url URL                  Set the URL for the Bitwarden server. Defaults to ${defaultServerUrl}"
     echo "    --restore PATH                 Restore using the backup file at PATH."
     echo "    -i, --identity IDENTITY        Restore using the identity (private key) file at IDENTITY. May be repeated."
@@ -44,6 +44,7 @@ usage() {
     echo
     echo "    BW_CLIENTID                    Set the Bitwarden API key (REQUIRED)."
     echo "    BW_CLIENTSECRET                Set the Bitwarden API key secret (REQUIRED)."
+    echo "    BW_BACKUP_PREFIX               Set default backup name prefix."
     echo "    BW_BACKUP_RECIPIENT            Set default recipient. May be a path to a recipients file."
     echo "    BW_BACKUP_DIR                  Set the default backup directory."
     echo "    BW_BACKUP_SECURE_TEMP_DIR      Set the default secure temp directory. Use '@' to create a path via $(ansi italic mktemp)."
@@ -61,7 +62,7 @@ main() {
     else
         backupVault
     fi
-    logoutFromVault
+    logoutFromVault verbose
 }
 
 init() {
@@ -70,9 +71,8 @@ init() {
     readonly scriptName="$(basename "${0}")"
     declare -grx PINENTRY_PROGRAM="${RAYVN_BIN_DIR}/rayvn-pinentry"
     readonly rageProjectUrl='https://github.com/str4d/rage'
-    readonly passwordVisibility="none"
     readonly defaultServerUrl="https://vault.bitwarden.com"
-    vaultName=
+    namePrefix="${BW_BACKUP_PREFIX}"
     vaultUrl=
     identities=
     restoreFile=
@@ -95,7 +95,7 @@ init() {
         -R | --recipients-file) shift; assertFile "${1}" "recipients file"; appendVar recipients "-R ${1}" ;;
         -i | --identity) shift; assertFile "${1}" "identities file"; appendVar identities "-i ${1}" ;;
         -b | --backup-dir) shift; setDirVar backupDir "${1}" "backup dir path" ;;
-        -n | --name) shift; vaultName="${1}" ;;
+        -p | --prefix) shift; namePrefix="${1}" ;;
         -u | --url) shift; vaultUrl="${1}" ;;
         -h | --help) usage ;;
         -v | --version) version "${BW_BACKUP_VERSION}" ;;
@@ -104,19 +104,17 @@ init() {
         shift
     done
 
-    require 'core/readpass'
     if [[ ${restoreFile} ]]; then
         [[ ${identities} ]] || fail "one or more identities required"
     else
         [[ ${recipients} ]] || fail "one or more recipients required"
     fi
 
-    [[ ${vaultName} ]] || vaultName="${USER}"
+    [[ ${namePrefix} ]] || namePrefix="${USER}"
     [[ ${vaultUrl} ]] || vaultUrl="${defaultServerUrl}"
-    readonly backupName="${vaultName}-backup-$(timeStamp)"
+    readonly backupName="${namePrefix}-backup-$(timeStamp)"
 
     if [[ ${backupDir} ]]; then
-        [[ -d ${backupDir} ]] || fail "Backup directory ${backupDir} not found"
         backupFile="${backupDir}/${backupName}.tar.gz.age"
     else
         backupFile="${backupName}.tar.gz.age"
@@ -184,25 +182,33 @@ ensureLatestCLI() {
         echo "${update}"
         fail
     fi
-    echo "Latest CLI is installed at $(ansi bold_green "$(which bw)")"
+    echo "Up to date. Using CLI at $(ansi bold_green "$(which bw)")"
 }
 
 loginToVault() {
     session=
 
     echo
-    echo "$(ansi bold_blue Login to vault)"
+    echo "$(ansi bold_blue Logging in to vault)"
+    echo
+    startBackgroundSpinner
 
     logoutFromVault force # just in case there is an active session
     bw config server "${vaultUrl}" > /dev/null
-    bw login --apikey > /dev/null || fail
+    bw login --apikey > /dev/null || fail "login failed"
 
-    for i in {1..3}; do
-        echo
-        session="$(bw unlock --raw)" && break
-    done
-
+    if [[ ${BW_BACKUP_DEV_PWD} ]]; then
+        session="$(bw unlock --raw --passwordenv BW_BACKUP_DEV_PWD)"
+    else
+        for i in {1..3}; do
+            echo
+            session="$(bw unlock --raw)" && break
+        done
+    fi
+    stopBackgroundSpinner true
     [[ ${session} ]] || fail "login failed"
+
+    echo "$(ansi bold_green Logged in.)"
 }
 
 syncVault() {
@@ -220,10 +226,10 @@ backupVault() {
     echo
     echo "$(ansi bold_blue Backing up vault)  "
     echo
-    echo -n "$(ansi italic working) "
+    #echo -n "$(ansi italic working) "
     startBackgroundSpinner
 
-    bw export --raw --format json --session "${session}" >"${vaultFile}" || fail
+    bw export --raw --format json --session "${session}" >"${vaultFile}" || failSpin
 
     items="$(bw list items --session "${session}")"
 
@@ -244,16 +250,15 @@ backupVault() {
             # get attachment
 
             bw get attachment "${attachmentId}" --itemid "${attachmentItemId}" --session="${session}" \
-                --output "${attachDir}/${fileName}" >/dev/null 2>&1 || fail
+                --output "${attachDir}/${fileName}" >/dev/null 2>&1 || failSpin
         done
     done
 
-    tar cz "${backupName}" | rage ${recipients} > ${backupFile} || fail
+    tar cz "${backupName}" | rage ${recipients} > ${backupFile} || failSpin
     local size="$(du -h "${backupFile}" | cut -d' ' -f2 | cut -d $'\t' -f1)"
 
-    stopBackgroundSpinner
-    eraseCurrentLine
-    echo "$(ansi bold_green Vault backed up to ${backupFile}) size: $(ansi bold ${size})"
+    stopBackgroundSpinner true
+    echo "Vault backed up to $(ansi bold_green ${backupFile}) size: $(ansi bold ${size})"
 }
 
 restoreVault() {
@@ -303,7 +308,15 @@ logoutFromVault() {
         bw logout > /dev/null 2>&1
     elif [[ ${session} ]]; then
         unset session
-        bw logout > /dev/null 2>&1
+        if [[ ${1} == verbose ]]; then
+            echo
+            echo "$(ansi bold_blue Logging out of vault)  "
+            echo
+            bw logout > /dev/null 2>&1
+            echo "$(ansi bold_green Logged out.)"
+        else
+            bw logout > /dev/null 2>&1
+        fi
     fi
 }
 
