Added createFolder

diff --git a/bin/bw-backup b/bin/bw-backup
--- a/bin/bw-backup
+++ b/bin/bw-backup
@@ -79,7 +79,7 @@ init() {
     readonly defaultServerUrl="https://vault.bitwarden.com"
     readonly backupFileSuffix="tar.gz.age"
     readonly restoreFolderPrefix="🔥"
-
+    BW_SESSION=
     namePrefix="${BW_BACKUP_PREFIX}"
     vaultUrl=
     identities=
@@ -120,7 +120,7 @@ init() {
 
     [[ ${namePrefix} ]] || namePrefix="${USER}"
     [[ ${vaultUrl} ]] || vaultUrl="${defaultServerUrl}"
-    readonly backupName="${namePrefix}-backup-$(epochSeconds)-$(timeStamp)"
+    readonly backupName="${namePrefix}-backup-$(timeStamp)"
 
     if [[ ${backupDir} ]]; then
         backupFile="${backupDir}/${backupName}.${backupFileSuffix}"
@@ -194,12 +194,10 @@ ensureLatestCLI() {
 }
 
 loginToVault() {
-    session=
-
     echo
     echo "$(ansi bold_blue Logging in to vault)"
     echo
-    startBackgroundSpinner
+    startSpinner
 
     logoutFromVault force # just in case there is an active session
     bw config server "${vaultUrl}" > /dev/null
@@ -210,28 +208,28 @@ loginToVault() {
 
         bw login --apikey > /dev/null || fail "login failed"
         if [[ ${BW_BACKUP_DEV_PWD} ]]; then
-            session="$(bw unlock --raw --passwordenv BW_BACKUP_DEV_PWD)"
+            BW_SESSION="$(bw unlock --raw --passwordenv BW_BACKUP_DEV_PWD)"
         else
-            for i in {1..3}; do
+            for retryIndex in {1..3}; do
                 echo
-                session="$(bw unlock --raw)" && break
+                BW_SESSION="$(bw unlock --raw)" && break
             done
         fi
-        stopBackgroundSpinner true
+        stopSpinner true
     else
-        stopBackgroundSpinner true
+        stopSpinner true
         if [[ ${BW_BACKUP_DEV_PWD} ]]; then
-            session="$(bw login --raw --passwordenv BW_BACKUP_DEV_PWD)"
+            BW_SESSION="$(bw login --raw --passwordenv BW_BACKUP_DEV_PWD)"
         else
-            for i in {1..3}; do
+            for retryIndex in {1..3}; do
                 echo
-                session="$(bw login --raw)" && break
+                BW_SESSION="$(bw login --raw)" && break
             done
         fi
         echo
     fi
 
-    [[ ${session} ]] || fail "login failed"
+    [[ ${BW_SESSION} ]] || fail "login failed"
 
     echo "$(ansi bold_green Logged in.)"
 }
@@ -252,11 +250,11 @@ backupVault() {
     echo "$(ansi bold_blue Backing up vault)  "
     echo
     #echo -n "$(ansi italic working) "
-    startBackgroundSpinner
+    startSpinner
 
-    bw export --raw --format json --session "${session}" >"${vaultFile}" || failSpin
+    bw export --raw --format json > "${vaultFile}" || failSpin
 
-    items="$(bw list items --session "${session}")"
+    items="$(bw list items )"
 
     attachmentItemIds="$(echo ${items} | jq -r ".[] | select(.attachments).id")"
 
@@ -265,16 +263,16 @@ backupVault() {
         attachments="$(echo "${item}" | jq -r ".attachments")"
         length="$(echo "${attachments}" | jq -r ". | length")"
 
-        for ((i = 0; i < ${length}; i++)); do
+        for ((retryIndex = 0; retryIndex < ${length}; retryIndex++)); do
             attachDir="$(makeDir ${attachmentsDir} ${attachmentItemId})"
 
-            attachment="$(echo "${attachments}" | jq ".[${i}]")"
+            attachment="$(echo "${attachments}" | jq ".[${retryIndex}]")"
             attachmentId="$(echo "${attachment}" | jq -r ".id")"
             fileName="$(echo "${attachment}" | jq -r ".fileName")"
 
             # get attachment
 
-            bw get attachment "${attachmentId}" --itemid "${attachmentItemId}" --session="${session}" \
+            bw get attachment "${attachmentId}" --itemid "${attachmentItemId}" \
                 --output "${attachDir}/${fileName}" >/dev/null 2>&1 || failSpin
         done
     done
@@ -282,7 +280,7 @@ backupVault() {
     tar cz "${backupName}" | rage ${recipients} > ${backupFile} || failSpin
     local size="$(du -h "${backupFile}" | cut -d' ' -f2 | cut -d $'\t' -f1)"
 
-    stopBackgroundSpinner true
+    stopSpinner true
     echo "$(ansi bold_green Vault backed up to) ${backupFile} $(ansi bold_green size): $(ansi bold ${size})"
 }
 
@@ -295,22 +293,72 @@ restoreVault() {
     local backupFile="${restoreFile}"
     local backupFileName="$(basename ${backupFile})"
     local backupDate="$(basename ${backupFileName#*backup-*-} .${backupFileSuffix})"
-    local backupSeconds="$(echo ${backupFileName##*backup-} | cut -d'-' -f1)"
-    local currentSeconds=$(epochSeconds)
-    local restoreFolder="${restoreFolderPrefix} ${backupDate}"
-    # printVar backupFile backupFileName backupDate backupSeconds currentSeconds # TODO REMOVE
-
-    local reply
+    local folderName=
+    local folderId=
 
     echo
-    echo "$(ansi bold Restoring) $(ansi bold_green ${backupFileName})"
+    echo "$(ansi bold_blue Restoring vault)"
     echo
-    echo -n "Checking vault "
-    startBackgroundSpinner
+    echo "Restoring vault from $(ansi bold_green ${backupFileName})"
+    echo
+
+    createFolder "${restoreFolderPrefix} ${backupDate}" folderName folderId
+    echo
+    echo "Restoring into folder '${folderName}'"
+
+    # printVar folderName folderId
+}
+
+createFolder() {
+    local baseFolder="${1}"
+    local -n resultName="${2}"
+    local -n resultId="${3}"
+    resultName=
+    resultId=
+
+    echo -n "Creating folder for restored items "
+    startSpinner
+
+    # Make sure we have a unique folder name, in case this has previously been restored
+
+    local checkFolder="${baseFolder}"
+    local retryIndex=
+    local retryCount=0
+
+    for retryIndex in {1..100}; do
+
+        # Does the folder already exist?
+
+        local existingFolder="$(bw get folder "${checkFolder}" 2>&1)" # just in case multiple already exist
+        if [[ ${existingFolder} =~ Not ]]; then
+            resultName="${checkFolder}" # No, so use this one.
+            break;
+        else
+            (( retryCount++ ))
+            checkFolder="${baseFolder}.${retryIndex}" # Yes, so update suffix
+        fi
+    done
+    [[ ${resultName} ]] || fail "Too many existing folders for this backup!"
+
+    # Create the folder
+
+    local defaultJson="$(bw get template folder)"
+    local encodedFolder="$(echo "${defaultJson/Folder name/${resultName}}" | bw encode)"
+    resultId="$(bw create folder "${encodedFolder}"  | jq -r ".id")"
+    stopSpinner true
+
+    if (( ${retryCount} == 1 )); then
+         warn "A folder for this backup already exists, added suffix to make unique."
+    elif (( ${retryCount} > 1 )); then
+        warn "${retryIndex} folders for this backup already exist, added suffix to make unique."
+    fi
+}
+
+checkVault() { # TODO REMOVE!
 
     # Does the folder already exist?
 
-    local existingFolder="$(bw get folder "${restoreFolder}" --session "${session}" 2> /dev/null)"
+    local existingFolder="$(bw get folder "${restoreFolder}" 2> /dev/null)"
     if [[ ${existingFolder} ]]; then
 
         # TODO: maybe offer to delete the folder and all items in it??
@@ -321,7 +369,7 @@ restoreVault() {
 
     # No. Are there existing items?
 
-    local existingItems="$(bw list items --session "${session}")"
+    local existingItems="$(bw list items)"
     local existingItemsCount=$(echo "${existingItems}" | jq length)
     if (( ${existingItemsCount} > 0 )); then
 
@@ -342,7 +390,7 @@ restoreVault() {
             fi
         done
 
-        stopBackgroundSpinner true
+        stopSpinner true
 
         if (( ${newerItemCount} == 0 )); then
             warn "Your vault has ${existingItemsCount} existing items."
@@ -360,20 +408,7 @@ restoreVault() {
         [[ ${reply,,} == 'yes' ]] || fail
         echo
     fi
-
-    # Create the folder
-
-    echo -n "Creating folder '${restoreFolder}' for restored items "
-    startBackgroundSpinner
-    local defaultJson="$(bw get template folder --session "${session}")"
-    local encodedFolder="$(echo "${defaultJson/Folder name/${restoreFolder}}" | bw encode)"
-    local folderId="$(bw create folder "${encodedFolder}" --session "${session}" | jq -r ".id")"
-    stopBackgroundSpinner true
-
-    echo "${restoreFolder} id: ${folderId}"
 }
-
-
 
 
 
@@ -381,8 +416,8 @@ restoreVault() {
 logoutFromVault() {
     if [[ ${1} == force ]]; then
         bw logout > /dev/null 2>&1
-    elif [[ ${session} ]]; then
-        unset session
+    elif [[ ${BW_SESSION} ]]; then
+        unset BW_SESSION
         if [[ ${1} == verbose ]]; then
             echo
             echo "$(ansi bold_blue Logging out of vault)  "
