Refactor login/unlock.

diff --git a/bin/valt b/bin/valt
--- a/bin/valt
+++ b/bin/valt
@@ -243,7 +243,7 @@ prepareVault() {
     debugStatus
     if ! useParentSession; then
         ensureLatestCLI
-        loginToVault
+        unlockVault
     fi
     syncVault
 }
@@ -272,11 +272,11 @@ ensureLatestCLI() {
 }
 
 sessionStatus() {
-    bw status | jq -r .status
+    bw status | jq -r '.status'
 }
 
-loginToVault() {
-    startSpinner "Logging in to vault"
+unlockVault() {
+    startSpinner "Unlocking vault"
 
     logoutFromVault force # just in case there is an active session
     declare -gx BW_SESSION
@@ -285,36 +285,48 @@ loginToVault() {
 
     if [[ ${BW_CLIENTID} ]]; then
 
-        # Use api key
+        # Use api key to login
 
-        bw login --apikey > /dev/null || fail "login failed"
-        if [[ ${VALT_BACKUP_DEV_PWD} ]]; then
-            BW_SESSION="$(bw unlock --raw --passwordenv VALT_BACKUP_DEV_PWD)"
-            stopSpinner "${doneCheck}"
-        else
-            stopSpinner ". Credentials required..."
-            for retryIndex in {1..3}; do
-                echo
-                BW_SESSION="$(bw unlock --raw)" && break
-            done
-        fi
+        bw login --apikey > /dev/null || failSpin "login with api key failed"
+
+        # Unlock vault
+
+        openVault unlock
+
     else
-        if [[ ${VALT_BACKUP_DEV_PWD} ]]; then
-            BW_SESSION="$(bw login --raw --passwordenv VALT_BACKUP_DEV_PWD)"
-            stopSpinner "${doneCheck}"
-        else
-            stopSpinner ". Credentials required..."
-            for retryIndex in {1..3}; do
-                echo
-                BW_SESSION="$(bw login --raw)" && break
-            done
-        fi
-        echo
+
+        # Login and unlock without api key
+
+        openVault login
     fi
 
-    [[ ${BW_SESSION} ]] || fail "login failed"
+    [[ ${BW_SESSION} ]] || failSpin "unlock failed"
 }
 
+openVault() {
+    local command=${1}
+    if [[ ${VALT_BACKUP_DEV_PWD} ]]; then
+        useDevPassword ${command}
+    else
+        useCredentials ${command}
+    fi
+}
+useDevPassword() {
+    local command=${1}
+    debug "useDevPassword ${command}"
+    [[ ${command} == login ]] && stopSpinner ". Credentials required..."
+    BW_SESSION="$(bw ${command} --raw --passwordenv VALT_BACKUP_DEV_PWD)"
+    [[ ${command} == unlock ]] && stopSpinner "${doneCheck}"
+}
+useCredentials() {
+    local command=${1}
+    stopSpinner ". Credentials required..."
+    debug "useCredentials ${command}"
+    for retryIndex in {1..3}; do
+        echo
+        BW_SESSION="$(bw ${command} --raw)" && break
+    done
+}
 syncVault() {
     startSpinner "Syncing vault"
     bw sync > /dev/null || fail
@@ -470,6 +482,7 @@ restoreVault() {
 
     logoutFromVault
 
+    echo
     echo "$(ansi bold_green Restore completed.)"
     echo
     echo "A note named '${restoreNoteName}' was added to your vault with details of this operation."
@@ -631,10 +644,12 @@ logoutFromVault() {
 
 cleanup() {
     logoutFromVault
+
+    [[ ${debug} ]] && exec 3<&- # close file descriptor
+
     if [[ ${generatedTempDir} ]]; then
         rm -rf "${generatedTempDir}" > /dev/null 2>&1 || warn "Failed to delete temp dir: ${generatedTempDir}"
     fi
-    [[ ${debug} ]] && exec 3<&-
 }
 
 # Load core library
